# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14YX5cswTdnNCygYOJDdmA-aK-UGj7CXx
"""

import pandas as pd

cols = [1,3,4,5,6]
df_jan = pd.read_csv('https://fis51.ru/web/form?date=2022-01',
                 sep=';',
                 usecols=cols,
                 parse_dates=['created_at'])
df_jan = df_jan.drop_duplicates(subset=['phone'], keep='last', inplace=False, ignore_index=True)

df_feb = pd.read_csv('https://fis51.ru/web/form?date=2022-02',
                 sep=';',
                 usecols=cols,
                 parse_dates=['created_at'])
df_feb = df_feb.drop_duplicates(subset=['phone'], keep='last', inplace=False, ignore_index=True)
df_mar = pd.read_csv('https://fis51.ru/web/form?date=2022-03',
                 sep=';',
                 usecols=cols,
                 parse_dates=['created_at'])
df_mar = df_mar.drop_duplicates(subset=['phone'], keep='last', inplace=False, ignore_index=True)
df_apr = pd.read_csv('https://fis51.ru/web/form?date=2022-04',
                 sep=';',
                 usecols=cols,
                 parse_dates=['created_at'])
df_apr = df_apr.drop_duplicates(subset=['phone'], keep='last', inplace=False, ignore_index=True)
df_may = pd.read_csv('https://fis51.ru/web/form?date=2022-05',
                 sep=';',
                 usecols=cols,
                 parse_dates=['created_at'])
df_may = df_may.drop_duplicates(subset=['phone'], keep='last', inplace=False, ignore_index=True)
df_jun = pd.read_csv('https://fis51.ru/web/form?date=2022-06',
                 sep=';',
                 usecols=cols,
                 parse_dates=['created_at'])
df_jun = df_jun.drop_duplicates(subset=['phone'], keep='last', inplace=False, ignore_index=True)

df_jul = pd.read_csv('https://fis51.ru/web/form?date=2022-07',
                 sep=';',
                 usecols=cols,
                 parse_dates=['created_at'])
df_jul = df_jul.drop_duplicates(subset=['phone'], keep='last', inplace=False, ignore_index=True)

df = pd.concat([df_jan,df_feb,df_mar,df_apr,df_may,df_jun,df_jul])

df.loc[(df.form=='Форма заказа'),'form']='Форма'
df.loc[(df.form=='Popapp с сайта fis51.ru'),'form']='Popapp'
df.loc[(df.city=='Мурманск - Лобова; 5'),'city']=1
df.loc[(df.city=='Мурманск - Полярные Зори; 25/1'),'city']=6
df.loc[(df.city=='Мурманск - Беринга; 6'),'city']=10
df.loc[(df.city=='Мурманск - Крупской; 2'),'city']=7
df.loc[(df.city=='Североморск - Душенова; 18'),'city']=11
df.loc[(df.city=='Мурмаши - Советская; 8'),'city']=22
df.loc[(df.city=='Снежногорск - Октябрьская; 14А'),'city']=20
df.loc[(df.city=='Заполярный - Ленина; 7'),'city']=21
df.loc[(df.city=='Оленегорск - Строительная; 31'),'city']=13
df.loc[(df.city=='Мончегорск - Металлургов; 34'),'city']=14
df.loc[(df.city=='Апатиты - Бредова; 19'),'city']=16
df.loc[(df.city=='Кировск - Ленина; 18'),'city']=18
df.loc[(df.city=='Ковдор - Кошица; 2'),'city']=15
df.loc[(df.city=='Полярные зори - Строителей; 8А'),'city']=19
df.loc[(df.city=='Кандалакша - Аэронавтов; 1/50'),'city']=17
df.loc[(df.city=='Полярный - Гагарина; 6'),'city']=33
repl=['\+',' ','-','\(','\)']
df.phone = df.phone.replace(repl,'',regex=True)
df['phone'] = df['phone'].astype(str)
df['phone'] = df['phone'].str.replace(r'^7', '')
df['phone'] = df['phone'].str.replace(r'^8', '')

df
